### ISSUE TITLE
provider makes Packages a required attributes

### ISSUE THREAD

**Issue by mpechner** [mmmorris1975/yumrepo_server#2]
You can see the my fork with the fix.  

pkg_files.path about line 35 in provider/default.rb.  Is done whether packages is nil or not.

**Comment by mmmorris1975** [comment]
Please check my branch pkg_path_fix to see if that's doing what you want.  Thanks for finding this!

**Comment by mpechner** [comment]
Yup, looks correct.  Thanks.

What is the process of getting this version into the supermarket?

On Mon, Aug 17, 2015 at 8:35 AM, Mike Morris <notifications@github.com>
wrote:

> Please check my branch pkg_path_fix to see if that's doing what you want.
> Thanks for finding this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmmorris1975/yumrepo_server/issues/2#issuecomment-131865340>
> .
>



-- 
Michael Pechner
NE6RD - Amateur Extra
mikey@mikey.com

**Comment by mmmorris1975** [comment]
Updates have been released to supermarket as version 0.1.5.

**Comment by mpechner** [comment]
Put your copy in place.  Worked as expected.  Thanks again.

On Wed, Aug 19, 2015 at 7:08 AM, Mike Morris <notifications@github.com>
wrote:

> Closed #2 <https://github.com/mmmorris1975/yumrepo_server/issues/2>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mmmorris1975/yumrepo_server/issues/2#event-386537226>.
>



-- 
Michael Pechner
NE6RD - Amateur Extra
mikey@mikey.com
