### ISSUE TITLE
Error installing on Centos 7 - unidentified node attribute

### ISSUE THREAD

**Issue by mfleishman** [mmmorris1975/yumrepo_server#3]
Hello,
I am trying to install the yumrepo_server cookbook on to a Chef client running version 12 and I am receiving this error:

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/yumrepo_server/recipes/default.rb
================================================================================

NoMethodError
-------------
Undefined node attribute or method `<<' on `node'. To set an attribute, use `<<=value' instead.

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/yumrepo_server/recipes/default.rb:23:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/yumrepo_server/recipes/default.rb:

 16:  # Going to use Apache web server, vs a lighter-weight HTTP
 17:  # server, since it's the only option available without
 18:  # needing to install the EPEL yum repo
 19:  #
 20:  # Needs lots of changes to make apache work in Fedora 18/19/20 (apache 2.4)
 21:  # Not going to bother testing older Fedora's since the project moves so fast,
 22:  # anything older is obsolete/unsupported
 23>> node.default['apache']['listen_ports'] << node['yum']['server']['http_port']
 24:  include_recipe 'apache2'
 25:  
 26:  if node['apache']['include_logrotate']
 27:    # apache2 version 3.1+ cookbook no longer include bundled
 28:    # logrotate recipe, emulate it here
 29:    include_recipe 'logrotate'
 30:  
 31:    logrotate_app 'httpd' do
 32:      path "#{node['apache']['log_dir']}/*.log"

[2015-12-15T23:01:49-08:00] ERROR: Running exception handlers
[2015-12-15T23:01:49-08:00] ERROR: Exception handlers complete
[2015-12-15T23:01:49-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-12-15T23:01:49-08:00] ERROR: Undefined node attribute or method `<<' on `node'. To set an attribute, use `<<=value' instead.
[2015-12-15T23:01:49-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

Has anyone run across this issue?

Thanks

**Comment by mmmorris1975** [comment]
Thanks!  This is the first I've heard of this issue.  I'll dig into it and let you know when it fixed.

**Comment by mmmorris1975** [comment]
I've run version 0.2.0 of the cookbook through test-kitchen using chef versions 12.0.1, 12.1.1, 12.2.1, 12.3.0, 12.4.1, 12.5.1, and 12.6.0 (latest), and was unable to duplicate this error.  Could you please pass along the version of the cookbook and chef you are using when you see this error?

**Comment by mfleishman** [comment]
Mike,

Thanks for responding.  The other issue that I ran into was with the
web_app.conf.erb file, some of the apache syntax may be for version 2.2
instead of 2.4.  I had to change settings from "Order allow,deny" to
"Require all granted".  I also commented out the following lines in the
file as it gave an error of not being there:

#RewriteLog <%= node['apache']['log_dir'] %>/<%= @application_name
%>-rewrite.log
  #RewriteLogLevel 0

After making those changes it is working for me right now.

Thank you for the help.

Mark

**Comment by mfleishman** [comment]
The error has not happened again to me, I believe it was an orchestration
issue for me and the way it ran through the Chef runlist. I did have to
make the changes to the web_app_conf.erb file.

**Comment by mmmorris1975** [comment]
Good deal.  I'll take a look at those web_app_conf.erb settings

**Comment by edwardbartholomew** [comment]
Receiving this error in CentOS 6 and CentOS 7 when running this cookbook with apache2 (v3.2.2) as listen_ports has been deprecated per https://github.com/svanzoest-cookbooks/apache2/blob/master/CHANGELOG.md
When I use this cookbook with apache2 (v3.1.0), I experience no errors.
