### ISSUE TITLE
can not use listen_ports with apache2 v3.2.x

### ISSUE THREAD

**Issue by mmmorris1975** [mmmorris1975/yumrepo_server#4]
Receiving this error in CentOS 6 and CentOS 7 when running this cookbook with apache2 (v3.2.2) as listen_ports has been deprecated per https://github.com/svanzoest-cookbooks/apache2/blob/master/CHANGELOG.md
When I use this cookbook with apache2 (v3.1.0), I experience no errors.

**Comment by mmmorris1975** [comment]
@edwardbartholomew Sorry it's taken so long to get to this $REAL_JOB has been keeping me busy.  I've opened a separate issue for this and should have a fix pushed today (expect version 0.3.0 of this cookbook to have the fix)

**Comment by mmmorris1975** [comment]
Fixed as part of 0.3.0 release of this cookbook, see commit 57fd225

**Comment by edwardbartholomew** [comment]
@mmmorris1975 Awesome, works great for me now, thank you!
